default: help

help:
	@echo "Usage: make [options] target"
	@echo ""
	@echo "Targets"
	@echo "    clean        Remove all files generated by this makefile."
	@echo ""
	@echo "Options"
	@echo "    -B           Force rule to always execute."

test-layer:
	rm -rf output
	python localtest.py -i examples/article -o output/docker --compile-with docker
	python localtest.py -i examples/article -o output/native --compile-with native
