default: help

# Always run these rules.
.PHONY: build package localtest localtest-quick clean


# Display make information when no commands are given.
help:
	@echo "Usage: make [options] target"
	@echo ""
	@echo "Targets"
	@echo "    localtest    Run a test with the built package locally."
	@echo "    clean        Remove all files generated by this makefile."
	@echo ""
	@echo "Options"
	@echo "    -B           Force rule to always execute."


# Run a quick testcase with a pristine docker environment and our built layer.
# The localtest-quick target speeds up the process by running only the test
# function, assuming that the testing environment is already set up.
# TODO verify localtest* works
localtest: build package
	rm -rf /tmp/lambdalatex
	mkdir -p /tmp/lambdalatex/opt
	cp build/lambdalatex.zip /tmp/lambdalatex/opt
	cd /tmp/lambdalatex/opt && unzip -q lambdalatex.zip
	rm /tmp/lambdalatex/opt/lambdalatex.zip
	make localtest-quick
	rm -rf /tmp/lambdalatex

localtest-quick:
	docker run --rm -v ${PWD}:/var/task -v /tmp/lambdalatex/opt:/opt lambci/lambda:python3.7 localtest.localtest


# Remove all built artifacts.
clean:
	$(MAKE) -C lambdalatex-layer clean
#	rm -f build/lambdalatex.zip
#	rm -f build/main.pdf
#	rm -rf build
#	rm -rf /tmp/lambdalatex
